name: Rust wasm32-wasi releases

on:
  release:
    types: [created]

jobs:
  release:
    name: release wasm32-wasi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: wasm32-wasi
          EXTRA_FILES: "readme.md LICENSE"
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v1
      - name: Publish to WAPM
        uses: wasmerio/wapm-publish@v1